version: "3.3"
services:
  #gluetun:
    #image: qmcgaw/gluetun:v3.34
    #container_name: gluetun
    # External Container --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    #cap_add:
    #  - NET_ADMIN
    #devices:
    #  - /dev/net/tun:/dev/net/tun
    #environment:
    #  # SetUp --> https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
    #  - VPN_SERVICE_PROVIDER=
    #  - VPN_TYPE=
    #  # OpenVPN --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/openvpn.md
    #  - OPENVPN_USER=  
    #  - OPENVPN_PASSWORD=
    #  # Wireguard --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/wireguard.md
    #  - WIREGUARD_PRIVATE_KEY=
    #  - WIREGUARD_ADDRESS=
    #  - WIREGUARD_PUBLIC_KEY=
    #  # TimeZone Logs --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/others.md
    #  - TZ=Asia/Kolkata
    #  # Server List Updater --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
    #  - UPDATER_PERIOD=24h
    #ports:
    #  - "80:80"
    #  - "8080:8080"
    #restart: on-failure
  app:
    build: .
    #network_mode: "service:gluetun" #If using VPN, Remove the Hash from first and fill up Above Details.
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
